name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: azcrdemo01.azurecr.io
          username: ${{ secrets.AZURECR_USERNAME }}
          password: ${{ secrets.AZURECR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . -t azcrdemo01.azurecr.io/myapp:latest
          docker push azcrdemo01.azurecr.io/myapp:latest

      - name: Azure Web App Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: az-cog
          slot-name: production
          images: azcrdemo01.azurecr.io/myapp:latest
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}